### ISSUE TITLE
--book option should create pages for .md files 

### ISSUE THREAD

**Issue by enw** [ultrasaurus/webgenr#3]
1. put `.md` and supporting files in `markdown` folder
2. run `webgenr`

EXPECTED:
markdown files are converted to XHTML, one chapter per markdown file
supporting files & generated XHTML are put into a new EPUB

ACTUAL:
one XHTML/Chapter is created for each file in the `markdown` folder
the EPUB can not be read.  Tested using `Apple Books` and `ebook-viewer` (installed w/Calibre)

```sh
(base) ➜  book-with-audio git:(main) ✗ webgenr --book        
processing source files from:   markdown
cover: markdown/_cover.svg
adding markdown/file_example_WAV_1MG.wav        as file_example_WAV_1MG.xhtml,  title: Chapter 1
adding markdown/butterfly.png   as butterfly.xhtml,     title: Chapter 2
adding markdown/file_example_MP3_700KB.mp3      as file_example_MP3_700KB.xhtml,        title: Chapter 3
adding markdown/file_example_OOG_1MG.ogg        as file_example_OOG_1MG.xhtml,  title: Chapter 4
adding markdown/index.md        as index.xhtml, title: Chapter 5
book created!
(base) ➜  book-with-audio git:(main) ✗ 
```

**Comment by enw** [comment]
what's the official way to say that I'm looking into a fix for this?

**Comment by enw** [comment]
looks like the issue is that anything other than cover & title page are turning into XHTML Chapters - `web.rs:217`

**Comment by ultrasaurus** [comment]
thanks for filing this!  I was actually thinking the source could be xhtml OR markdown, then forgot I hadn't implemented the markdown part.  
<img width="94" alt="image" src="https://user-images.githubusercontent.com/41906/230800925-903c9d1d-57e9-4352-aa72-82fdad72ed27.png">

**Comment by ultrasaurus** [comment]
updated to remove "only" -- I'll plan to support both (unless that turns out to be tricky for some reason... please chime in if there's a reason *not* to support `xhtml` or `html` source files (noting that it is legit for `.md` files to contain html so this is just a convenience for authors)

**Comment by ultrasaurus** [comment]
gonna close this as fixed.  Please open a more specific bug if you find further issues with creating a book from markdown pages
